
  /* ============================== new tour stops: the journey, the Gatehouse and the Deep ============================== */
  (function () {
    function gp(lx, lz, y) { var w = gw(lx, lz); return [w[0], y, w[1]]; }
    var mz0 = GZ0 - 28, cz0 = GZ1, cz1 = GZ1 + 28, y1 = LVY[1], y2 = LVY[2], y3 = LVY[3], y4 = LVY[4], y5 = LVY[5];
    var S = [
      { id: "spaceport", group: "The journey", name: "Arcadia Spaceport", where: "Transport centre · 1.4 km east", mode: "orbit", pos: [PORT.x - 330, 150, PORT.z + 300], look: [PORT.x, 8, PORT.z - 60], ceil: "open sky", shield: "blast walls", area: 180000, lv: 0,
        text: "Where every journey to the palace begins. Ships from Earth and from orbit land on three pads behind blast walls; you walk through the terminal and take a private air taxi the last 1.4 km to your door. In a dust storm, a maglev runs under the plain instead.",
        details: ["Three landing pads for 50 m ships", "Glass terminal with lounges and a customs hall", "Control tower and propellant farm", "Air-taxi pad and the maglev portal"],
        mars: ["Ships land on their engines; the blast walls stop the gravel they throw", "The propellant farm makes methane and oxygen from Martian air and ice, so ships refuel here for the trip home", "At 0.38 g an air taxi needs far less lift than on Earth, but the air is so thin it flies on ducted fans and thrusters together"] },
      { id: "portal", group: "Arrival & grounds", name: "Arrival pad & portal", where: "Grounds · the front door", mode: "stand", pos: gp(9, 47, 2.4), look: gp(0, 19, 5.5), ceil: "open sky", shield: "basalt pylons", room: "gate", areaOverride: 615, lv: 0,
        text: "Your air taxi sets you down here, 40 m from the door. A lit basalt walk leads to a portal of two basalt pylons under a bronze canopy. There is no keyhole: the house recognises you as you walk up and opens the airlock.",
        details: ["Air-taxi pad 28 m across with blue edge lights", "Basalt walk with bollard lights", "Pylons 13 m tall under a bronze canopy", "Identity scanner: face, iris and gait"],
        mars: ["Outside you are in a suit: the air is 0.6 % as thick as Earth's and mostly carbon dioxide", "The doors are an airlock, so the house never loses its air when you come home"] },
      { id: "gatehouse", group: "Arrival & grounds", name: "The Gatehouse", where: "Entrance hall · north-east of the dome", mode: "stand", pos: gp(2.8, 10.8, 1.7), look: gp(-1.5, -6, 0.9), ceil: "11 m", shield: "sintered regolith", room: "gate", lv: 0,
        text: "The entrance hall. Light falls in through tall slots between bronze fins onto a marble floor, and in the middle a glass oculus 12 m across looks straight down 104 m into the atrium of the Deep. Two glass lifts wait beside it.",
        details: ["Glass oculus over a 104 m drop", "Two glass lifts to all five underground levels", "Marble, bronze fins and a coffered walnut ceiling", "Link corridor into the Great Dome's garden"],
        mars: ["The airlock at the far end cycles in under a minute", "Most of the house is underground, where rock stops radiation and the temperature never changes"] },
      { id: "atrium", group: "The Deep · Salon level", name: "The grand atrium", where: "The Deep · all levels · 104 m", mode: "stand", pos: [AC.x + 19.2, y1 + 1.7, AC.z + 3], look: [AC.x - 20, y1 - 15, AC.z - 4], ceil: "104 m", shield: "the planet", rooms: ["atr1", "atr2", "atr3", "atr4", "atr5"], lv: 1,
        text: "The spine of the Deep: a round shaft 48 m across and 104 m deep, with a balcony ring at every level and two glass lifts running the full height on bridges. A slow wave of 640 polished brass spheres hangs in the middle, turning under the light from the Gatehouse oculus.",
        details: ["Five levels, from the Salon at −14 m to Transit at −104 m", "Glass lifts on bridges across the void", "Kinetic sculpture of 640 brass spheres", "Reflecting pool on the atrium floor"],
        mars: ["Ten metres of rock stop almost all cosmic radiation: every room down here is safer than any room above", "Dust storms can last months; down here nobody notices"] },
      { id: "gallery", group: "The Deep · Salon level", name: "The Long Gallery", where: "The Deep · Salon level · −14 m", mode: "stand", pos: [64, y1 + 1.8, AC.z + 3.4], look: [122, y1 + 2.4, AC.z - 1], ceil: "7 m", shield: "14 m rock", room: "gallery", lv: 1,
        text: "A 120 m gallery running east from the atrium: paintings on both walls, meteorites on plinths and a continuous light ceiling. Every room of the Salon level opens off it.",
        details: ["120 m of marble with a black marble inlay", "Paintings and meteorites", "Doors to seven salons"],
        mars: ["Artificial daylight follows the sol: cool at noon, warm in the evening"] },
      { id: "media", group: "The Deep · Salon level", name: "Media lounge", where: "The Deep · Salon level · TV & books", mode: "stand", pos: [92.5, y1 + 1.7, mz0 + 24.5], look: [80, y1 + 2.1, mz0 + 2], ceil: "6 m", shield: "14 m rock", room: "media", lv: 1,
        text: "Your TV and book room. A 6 m screen set in a walnut wall, shelves of books on both sides, a deep sectional sofa in cream bouclé and a fire. Sit down and switch it on: Earth live, the palace cameras, Mars weather or a film.",
        details: ["6.2 m screen with four channels", "Walls of books and a reading chaise", "Sectional sofa for ten", "Bioethanol fireplace in black marble"],
        mars: ["Earth programmes arrive 3 to 22 minutes late; the house records them and plays them when you sit down", "The palace cameras are live: switch to them to see the weather outside"] },
      { id: "cinema", group: "The Deep · Salon level", name: "Private cinema", where: "The Deep · Salon level", mode: "stand", pos: [82, y1 + 3.35, cz0 + 2.6], look: [82, y1 + 4, cz1], ceil: "8 m", shield: "14 m rock", room: "cinema", lv: 1,
        text: "Thirty-five leather recliners on five tiers in front of a 14 m screen, under a ceiling of fibre-optic stars. It is the quietest room in the house: nothing can be heard through fourteen metres of rock.",
        details: ["14 m screen", "35 heated leather recliners", "Star-field ceiling", "Acoustic fabric walls"],
        mars: ["New films take minutes to arrive from Earth but weeks by courier for full-resolution copies; both are kept in the AI core"] },
      { id: "library2", group: "The Deep · Salon level", name: "Grand library", where: "The Deep · Salon level", mode: "stand", pos: [AC.x + 3, y1 + 1.7, -78.4], look: [AC.x - 5, y1 + 5, -106], ceil: "11.5 m", shield: "12 m rock", room: "library2", lv: 1,
        text: "Two storeys of books round three walls, a gallery with a brass rail, two spiral stairs and long reading tables under green banker's lamps. Walk to any shelf and take a book down.",
        details: ["About 40,000 volumes on two storeys", "Gallery walkway and spiral stairs", "Reading tables for 42", "A 1.8 m Mars globe"],
        mars: ["Paper is a luxury on Mars: these books were printed here from cellulose grown in the farms", "In 0.38 g a full shelf weighs 38 % of what it would at home"] },
      { id: "music", group: "The Deep · Salon level", name: "Music room", where: "The Deep · Salon level", mode: "stand", pos: [117, y1 + 1.7, mz0 + 24], look: [106, y1 + 1, mz0 + 8], ceil: "6 m", shield: "14 m rock", room: "music", lv: 1,
        text: "A room tuned for sound: oak slats on the walls, a grand piano, guitars on their stands and a pair of tall speakers. You can play the piano.",
        details: ["Concert grand piano", "Three guitars", "Oak acoustic slats"],
        mars: ["Outside, sound barely carries in the thin air; in here it is warm and full"] },
      { id: "holo", group: "The Deep · Salon level", name: "Holodeck & games", where: "The Deep · Salon level", mode: "stand", pos: [152, y1 + 1.7, mz0 + 25], look: [132, y1 + 1.5, mz0 + 8], ceil: "6 m", shield: "14 m rock", room: "holo", lv: 1,
        text: "A glass-fronted holodeck where walls, floor and ceiling become any place on Earth, and a games room with billiards and a row of arcade cabinets.",
        details: ["Holodeck 36 m × 14 m", "Billiard table", "Arcade row", "Lounge chairs"],
        mars: ["Homesickness is real on Mars; the holodeck is prescribed as often as exercise"] },
      { id: "jazz", group: "The Deep · Salon level", name: "Jazz bar", where: "The Deep · Salon level", mode: "stand", pos: [161, y1 + 1.7, mz0 + 26], look: [176, y1 + 1.3, mz0 + 12], ceil: "5.5 m", shield: "14 m rock", room: "jazz", lv: 1,
        text: "Walnut panelling, a black marble bar, leather booths and a small stage with a piano and a double bass.",
        details: ["12 m black marble bar", "Three leather booths", "Stage with piano and bass"],
        mars: ["The cocktails pour slowly: liquids fall at 38 % of Earth's pull"] },
      { id: "skyhall", group: "The Deep · Salon level", name: "Sky Hall", where: "The Deep · Salon level · ballroom", mode: "stand", pos: [102.6, y1 + 1.7, cz0 + 2.6], look: [130, y1 + 6.5, cz0 + 16], ceil: "11.5 m", shield: "14 m rock", room: "skyhall", lv: 1,
        text: "A ballroom under a blue Earth sky, with clouds drifting across it. Marble floor, eighteen columns, round tables for dinner and a stage.",
        details: ["LED sky dome 50 m × 28 m", "Eighteen marble columns", "Dinner for 48", "Stage with a grand piano"],
        mars: ["The Earth sky is a screen, but after a year under Mars's butterscotch sky it feels like a holiday"] },
      { id: "sculpt", group: "The Deep · Salon level", name: "Sculpture court", where: "The Deep · Salon level", mode: "stand", pos: [152, y1 + 1.7, cz0 + 2], look: [168, y1 + 1.5, cz0 + 14], ceil: "7 m", shield: "14 m rock", room: "sculpt", lv: 1,
        text: "Six sculptures on stone plinths under their own lights: bronze knots and rings, a mirror sphere, basalt and marble forms.",
        details: ["Six works on plinths", "Paintings on the far wall"],
        mars: ["Heavy sculpture is easy to move here: a two-tonne bronze weighs what 760 kg would on Earth"] },
      { id: "baths", group: "The Deep · Salon level", name: "Thermal baths", where: "The Deep · Salon level · west", mode: "stand", pos: [-11, y1 + 2.4, -15], look: [-28, y1 + 0.2, -40], ceil: "9 m vault", shield: "14 m rock", room: "baths", lv: 1,
        text: "Roman baths under Mars: a 22 m warm pool, a hot pool and a cold pool, fourteen marble columns and a barrel vault. Steam rises all day.",
        details: ["Warm pool 22 m × 12 m", "Hot and cold round pools", "Loungers down both sides"],
        mars: ["The water is warmed by waste heat from the fusion plant, 74 m below"] },
      { id: "sports", group: "The Deep · Salon level", name: "Low-gravity sports hall", where: "The Deep · Salon level · south", mode: "stand", pos: [66.5, y1 + 1.8, 2.5], look: [30, y1 + 4, 30], ceil: "11 m", shield: "14 m rock", room: "sports", lv: 1,
        text: "Basketball with the rim at 7.8 m, because in 0.38 g everyone can dunk on a normal one. A running track round the edge and an 11 m climbing wall.",
        details: ["Court with 7.8 m rims", "Climbing wall 30 m wide, 11 m high", "Running track"],
        mars: ["You jump about 2.6 times as high as on Earth", "Running is odd: each stride carries you further, so the track is banked at the corners"] },
      { id: "grotto", group: "The Deep · The Grotto", name: "The Grotto", where: "The Deep · −40 m · lava tube", mode: "stand", pos: [150, y2 + 3.2, -40], look: [262, y2 + 2.5, -64], ceil: "23 m", shield: "17 m rock", room: "grotto", lv: 2,
        text: "A sealed lava tube 300 m long, turned into a beach: white sand, a warm lagoon, palm trees, a beach house and an Earth sky with a sun that sets every evening. At the far end a waterfall drops 18 m into the lagoon.",
        details: ["Lagoon 210 m × 64 m", "46 palms and a beach house", "Waterfall and hot-spring terraces", "LED sky with a moving sun"],
        mars: ["Lava tubes on Mars can be hundreds of metres wide: low gravity let them grow far larger than on Earth", "Sealed and pressurised, a tube like this needs no dome at all: the rock holds the air in"] },
      { id: "springs", group: "The Deep · The Grotto", name: "Hot springs", where: "The Deep · The Grotto", mode: "stand", pos: [152, y2 + 1.9, -68], look: [122, y2 + 0.5, -94], ceil: "23 m", shield: "17 m rock", room: "grotto", areaOverride: 900, lv: 2,
        text: "Four travertine terraces step down to the lagoon, each a warm pool, hotter at the top.",
        details: ["Four terrace pools, 34 °C to 40 °C", "Steam and the sound of water"],
        mars: ["Travertine forms from mineral water; this was cast from lime made on Mars"] },
      { id: "waterfall", group: "The Deep · The Grotto", name: "The waterfall", where: "The Deep · The Grotto · east end", mode: "stand", pos: [334, y2 + 1.8, -40], look: [372, y2 + 7, -56], ceil: "23 m", shield: "17 m rock", room: "grotto", areaOverride: 2000, lv: 2,
        text: "The lagoon's water is pumped to the top of a basalt cliff and falls 18 m back in. In Mars gravity it falls slower than you expect.",
        details: ["18 m fall", "Mist and basalt boulders"],
        mars: ["A drop takes 3.1 s to fall 18 m here, against 1.9 s on Earth"] },
      { id: "forest", group: "The Deep · Living Earth", name: "The forest", where: "The Deep · −64 m · Living Earth", mode: "stand", pos: [AC.x + 1, y3 + 1.7, -148], look: [28, y3 + 8, -232], ceil: "30 m", shield: "34 m rock", room: "forest", lv: 3,
        text: "A redwood forest in a cavern 220 m long: tall conifers, ferns, a stream with a wooden bridge and mist under a soft overcast sky. It is the lungs of the house and the place to remember Earth.",
        details: ["110 conifers up to 32 m tall", "Stream with stepping stones and a bridge", "A rain room in the clearing", "Picnic deck"],
        mars: ["In 0.38 g trees grow taller and thinner; these are cabled to the rock like young trees in a nursery", "The forest makes a large share of the house's oxygen"] },
      { id: "rainroom", group: "The Deep · Living Earth", name: "Rain room", where: "The Deep · Living Earth · clearing", mode: "stand", pos: [18, y3 + 1.9, -226], look: [18, y3 + 1.2, -236], ceil: "4 m", shield: "34 m rock", room: "forest", areaOverride: 81, lv: 3,
        text: "It never rains on Mars. In this glass pavilion it rains whenever you step inside: warm, soft and slow, because the drops fall at Mars gravity.",
        details: ["Glass pavilion with a rain ceiling", "Bench and a stool"],
        mars: ["Raindrops fall slower here, so they are bigger before they break up"] },
      { id: "farms", group: "The Deep · Living Earth", name: "Vertical farms", where: "The Deep · Living Earth · west", mode: "stand", pos: [-3.5, y3 + 1.7, -38], look: [-35, y3 + 7, -52], ceil: "22 m", shield: "34 m rock", room: "farms", lv: 3,
        text: "Racks of lettuce, herbs, berries and grain sixteen metres high under pink and white grow lights, and fish in four round tanks. This hall feeds the house.",
        details: ["56 towers, ten shelves each", "Aquaculture: four fish tanks", "Grow lights on a sol cycle"],
        mars: ["Food grown underground is safe from dust storms and solar flares", "Fish waste fertilises the plants; the plants clean the water"] },
      { id: "fusion", group: "The Deep · Engine level", name: "Fusion hall", where: "The Deep · −88 m · Engine level", mode: "stand", pos: [10, y4 + 7.9, 30.6], look: [50, y4 + 7, 70], ceil: "30 m", shield: "88 m rock", room: "fusion", lv: 4,
        text: "The house's power: a compact fusion reactor with its vessel cut away so you can see the plasma ring glowing inside eighteen D-shaped magnets. Seen from the control gallery.",
        details: ["Tokamak 31 m across", "Eighteen superconducting magnets", "Three turbine halls", "Gantry crane"],
        mars: ["Fusion is the future-proof option: fuel for centuries, no dependence on sunlight", "Waste heat warms the baths, the pools and the forest"] },
      { id: "fab", group: "The Deep · Engine level", name: "Fabrication hall", where: "The Deep · Engine level", mode: "stand", pos: [104, y4 + 1.7, 32.5], look: [150, y4 + 2, 70], ceil: "18 m", shield: "88 m rock", room: "fab", lv: 4,
        text: "Robots build and repair the house: six arms at assembly cells, a gantry printer laying regolith for new domes, and racks of drones.",
        details: ["Six robot arms", "Regolith printer 24 m × 26 m", "Drone racks"],
        mars: ["Almost everything here was printed from Martian regolith, metal and plastic made on site"] },
      { id: "works", group: "The Deep · Engine level", name: "Water & air works", where: "The Deep · Engine level", mode: "stand", pos: [-4, y4 + 1.7, 32], look: [-35, y4 + 5, 70], ceil: "14 m", shield: "88 m rock", room: "works", lv: 4,
        text: "Where ice becomes water and water becomes air: eight storage tanks, electrolysers splitting water into hydrogen and oxygen, and oxygen plants breathing Martian carbon dioxide.",
        details: ["Eight tanks, 11 m tall", "Four electrolyser stacks", "Oxygen from CO₂"],
        mars: ["Water is mined from ice under the palace", "NASA's MOXIE made oxygen from Martian air in 2021; these are its descendants"] },
      { id: "aicore", group: "The Deep · Engine level", name: "AI core", where: "The Deep · Engine level", mode: "stand", pos: [62, y4 + 1.7, 17.5], look: [85, y4 + 3.5, 6], ceil: "8 m", shield: "88 m rock", room: "aicore", lv: 4,
        text: "The house's mind: rows of servers round a quantum processor hung in its gold cryostat like a chandelier. It runs the air, the light, the robots and your films.",
        details: ["72 server racks", "Quantum processor in a gold cryostat", "Deepest room of the house after Transit"],
        mars: ["A message to Earth takes minutes, so the house must think for itself"] },
      { id: "vault", group: "The Deep · Engine level", name: "Seed vault & medical bay", where: "The Deep · Engine level", mode: "stand", pos: [10, y4 + 1.7, 17], look: [-20, y4 + 1.5, 4], ceil: "6 m", shield: "88 m rock", room: "vault", lv: 4,
        text: "A cold vault holding seeds and genetic samples of Earth's plants, and a medical bay with a robotic surgeon and three hibernation pods.",
        details: ["240 cold drawers", "Robotic surgery", "Three hibernation pods"],
        mars: ["The nearest hospital on Earth is months away; the house has to heal you itself"] },
      { id: "maglev", group: "The Deep · Transit", name: "Maglev station", where: "The Deep · −104 m · Transit", mode: "stand", pos: [84, y5 + 1.7, -44], look: [140, y5 + 1.5, -33], ceil: "12 m", shield: "104 m rock", room: "maglev", lv: 5,
        text: "The storm road: a private maglev capsule that runs 1.45 km under the plain to the spaceport in 38 seconds, whatever the weather above.",
        details: ["28 m capsule for twelve", "Glass platform doors", "Tunnel to the spaceport"],
        mars: ["When a dust storm grounds the air taxis, this is how you come and go"] },
      { id: "reserves", group: "The Deep · Transit", name: "Storm reserves", where: "The Deep · Transit", mode: "stand", pos: [10, y5 + 1.7, -38.5], look: [-25, y5 + 3, -40], ceil: "10 m", shield: "104 m rock", room: "reserves", lv: 5,
        text: "Two years of food, water and air for the household, in case the worst dust storm Mars has ever seen settles over Arcadia.",
        details: ["300 pallets of stores", "Three water tanks", "Spare parts for every machine"],
        mars: ["The 2018 global dust storm lasted months and ended the Opportunity rover's mission"] },
      { id: "atriumfloor", group: "The Deep · Transit", name: "Atrium floor", where: "The Deep · bottom of the atrium", mode: "stand", pos: [AC.x + 13, y5 + 1.7, AC.z + 11], look: [AC.x, y5 + 60, AC.z], ceil: "104 m", shield: "104 m rock", room: "atr5", lv: 5,
        text: "The bottom of the atrium, 104 m below the Gatehouse: a reflecting pool, and above it every balcony ring of the Deep and the sculpture of brass spheres.",
        details: ["Reflecting pool", "View up 104 m"],
        mars: ["At this depth the temperature of the rock is steady all year"] }
    ];
    S.forEach(function (s) { STOPS.push(s); });
    // the arrival stop now tells the whole story
    var ar = STOPS.filter(function (s) { return s.id === "arrival"; })[0];
    ar.text = "Arcadia Palace sits on the western rim of a mesa above Arcadia Planitia, 44° north. Above ground: a glass Great Dome, four wings buried under regolith, an observatory, three garden domes and the Gatehouse. Below ground lies the Deep: five levels more than ten times the size of the house above, from a beach cavern to a fusion plant.";
    ar.details = ["Great Dome 52 m across and 26 m high", "Gatehouse with an airlock and lifts to the Deep", "The Deep: five levels down to −104 m", "Arcadia Spaceport 1.4 km east, by air taxi or maglev"];
  })();
