/* The tour's stops: each is a 360° render of the 3D model (Blender Cycles, path-traced). Positions are in the
   family room's frame, in metres: x along the glass onto the atrium (y = 0), y into the room, z the height of the
   floor you stand on (0 = L1). az0 is where you look first (degrees: 0 = into the room, 90 = to the left,
   180 = out to the atrium). A link is a stop's id, or { id, at: [x, y, z] } to put its ring somewhere else (the portal). */
window.TOUR_STOPS = [
  { id: "fire", name: "By the fire", short: "The fire", k: "L1 · Jim's family room", p: [0.8, 11.3], az0: 20, img: "pano/fire.jpg",
    d: "The family room: a hearth of lit mist in a travertine chimney breast (no open flames in air with 27% oxygen), walnut shelves lit from within, an oak ceiling and a skylight full of the Sun Well's light. The doors either side go out to the street and the master suite.",
    links: ["glass", "piano", "table", { id: "bedroom", at: [2.9, 13.6, 0], label: "Through the door: the master suite" }] },
  { id: "glass", name: "At the glass", short: "The glass", k: "L1 · Jim's family room", p: [2.6, 1.1], az0: 180, img: "pano/glass.jpg",
    d: "The whole front of the room is glass onto the atrium gardens, with doors out to the terrace. A chess table in the light; the music room is through the wall to the left, the dining room to the right.",
    links: ["fire", "terrace", "piano", "table"] },
  { id: "piano", name: "The music room", short: "Music room", k: "L1 · Jim's residence", p: [-11.2, 6.2], az0: 172, img: "pano/piano.jpg",
    d: "The grand piano by the glass, a sofa and two chairs to listen from, and at the far end a wall of records with a turntable between two tall speakers and two armchairs. The opening in the wall goes through to the family room.",
    links: ["fire", "glass"] },
  { id: "table", name: "The dining room", short: "Dining room", k: "L1 · Jim's residence", p: [9.4, 9.8], az0: 196, img: "pano/table.jpg",
    d: "A walnut table for eight under five glass globes, a sideboard under a painting, shelves of books, and the atrium through the glass. The family room is through the opening.",
    links: ["fire", "glass"] },
  { id: "terrace", ready: false, name: "On the terrace", short: "Terrace", k: "L1 · The atrium", p: [0.0, -1.9], z: -0.02, az0: 180, img: "pano/terrace.jpg",
    d: "Outside the family room: olive trees and box hedges, vines trailing over the glass, Jim's study upstairs, and the bridge out to the portal column under the sky lens.",
    links: ["glass", "bridge"] },
  { id: "bridge", ready: false, name: "On the bridge", short: "Bridge", k: "L1 · The atrium, 24 m down", p: [0.0, -11.0], z: -0.02, az0: 140, img: "pano/bridge.jpg",
    d: "Halfway out to the portal column. The atrium goes on down 44 m to the sun court, past the garden level and the studios; the sky lens of the Sun Well is overhead. The portal at the end of the bridge goes to any level.",
    links: ["terrace", { id: "court", at: [0.6, -18.6, 1.4], label: "Portal: down to the sun court" }, { id: "crown_arrival", at: [-0.6, -18.6, 2.6], label: "Portal: up to the Crown" },
      { id: "library", at: [-14.16, -43.58, 0], label: "Across the atrium: the great library" }, { id: "baths", at: [14.16, -43.58, 0], label: "Across the atrium: the thermal baths" }, { id: "cinema", at: [22.91, -16.65, 0], label: "Across the atrium: the cinema" }] },
  { id: "court", ready: false, name: "The sun court", short: "Sun court", k: "L5 · 68 m down", p: [0.0, -35.6], z: -44.05, az0: 0, img: "pano/court.jpg",
    d: "The bottom of the atrium: a lawn with olive trees round a pool at the foot of the column, in the light of the sky lens 52 m above. Behind the glass all round are the halls of L5: the maglev, the freight portals, the seed vault and the rovers.",
    links: [{ id: "bridge", at: [2.9, -28.1, -42.5], label: "Portal: up to L1" }] },

  /* The master suite down, across the street behind the family room (ring B of sector 1). */
  { id: "bedroom", name: "The bedroom down", short: "Bedroom down", k: "L1 · Master suite down", p: [10.4, 23.4], az0: -87, img: "pano/bedroom.jpg",
    d: "Where Jim sleeps most nights: an upholstered headboard wall in vertical channels, walnut and pale oak, the bed facing the moss garden through the glass, two chairs by the window and sheer curtains.",
    links: [{ id: "garden", at: [6.4, 22.0, 0], label: "Out into the moss garden" }, "bath"] },
  { id: "garden", name: "The moss garden", short: "Moss garden", k: "L1 · Master suite down", p: [2.17, 21.6], z: 0.05, az0: 38, img: "pano/garden.jpg",
    d: "The heart of the suite, open to a sky ceiling: moss in cushions round a pond with maple leaves floating on it, a Japanese maple, a stone lantern that glows at night, a water basin fed by a bamboo spout, ferns and clipped box.",
    links: ["bedroom", "bath"] },
  { id: "bath", name: "The bath down", short: "Bath down", k: "L1 · Master suite down", p: [-11.6, 23.4], az0: 87, img: "pano/bath.jpg",
    d: "A stone tub facing the garden, a double vanity on a wall of green marble with round mirrors lit from behind, a walk-in shower with a rain head and a teak floor, oak on the walls.",
    links: [{ id: "garden", at: [-6.4, 22.0, 0], label: "Out into the moss garden" }, "bedroom"] },
  { id: "kitchen", name: "The kitchen", short: "Kitchen", k: "L1 · Jim's residence", p: [21.0, 22.4], az0: 200, img: "pano/kitchen.jpg",
    d: "The everyday kitchen, across the street from the dining room: walnut and stone along the back wall, open shelves of jars and crockery, an island to have breakfast at, and the robot that cooks on its rail under the ceiling. Jim can cook too.",
    links: [{ id: "table", at: [18.6, 17.6, 0], label: "Across the street: the dining room" }] },

  /* The other rooms of ring A on L1, each behind the glass of another side of the atrium. They are rendered in their
     own frame (the family room's, turned round the atrium's middle), so rot gives the map direction of the picture's
     middle; p is on the map. Full height, 7.6 m: the library, the baths and the cinema. */
  { id: "library", rot: 144, name: "The great library", short: "Great library", k: "L1 · The great library", p: [-18.69, -45.73], az0: 20, img: "pano/library.jpg",
    d: "Two storeys of books on three walls, 49 m along the back: walnut shelves washed with warm light, a gallery all round reached by a spiral stair, rolling ladders, long reading tables with brass lamps, leather chairs by the glass and a globe of the Earth.",
    links: [{ id: "bridge", at: [-13.81, -43.09, 0], label: "Out across the atrium, to the bridge" }, { id: "baths", label: "Next door: the thermal baths" }] },
  { id: "baths", rot: 216, name: "The thermal baths", short: "Thermal baths", k: "L1 · The baths", p: [23.35, -49.76], az0: 180, img: "pano/baths.jpg",
    d: "Grey-green quartzite laid in thin courses, blades of daylight through slots in the ceiling, and three pools: a long warm pool, a round hot pool and a cold plunge. Loungers along the glass look out at the atrium's gardens.",
    links: [{ id: "bridge", at: [13.81, -43.09, 0], label: "Out across the atrium, to the bridge" }, { id: "library", label: "Next door: the great library" }, { id: "cinema", label: "Next door: the cinema" }] },
  { id: "guests", rot: 72, name: "The guest lounge", short: "Guest lounge", k: "L1 · The guest lounge", p: [-28.24, -14.92], az0: -20, img: "pano/guests.jpg",
    d: "Where visitors from Earth and Jim meet in the evening, two storeys on the atrium glass: sofas round a low table by the glass, a walnut table for twelve under glass globes, and a gallery along the back wall with the doors of the guest suites and lamps between them.",
    links: [{ id: "bridge", at: [-23.20, -16.55, 0], label: "Out across the atrium, to the bridge" }, { id: "library", label: "Next door: the great library" }] },
  { id: "cinema", rot: 288, name: "The cinema", short: "Cinema", k: "L1 · The club", p: [24.43, -16.15], z: 1.26, az0: 0, img: "pano/cinema.jpg",
    d: "Forty velvet seats in four rows under a ceiling of stars, walnut walls, curtains drawn across the glass, and a screen 12 m wide. Tonight: the Earth.",
    links: [{ id: "bridge", at: [22.34, -16.83, 0], label: "Out across the atrium, to the bridge" }, { id: "baths", label: "Next door: the thermal baths" }] },

  { id: "memory", name: "The memory rooms", short: "Memory rooms", k: "L1 · Jim's residence", p: [0.4, 59.7], az0: 10, img: "pano/memory.jpg",
    d: "Jim's keepsakes from Earth: photographs of the places of his life hung close on walls of deep green under brass picture lights, two glass cases of letters, a pocket watch and the things he brought from home, the albums on a reading table, and the desk where he records his memoirs.",
    links: [{ id: "kitchen", label: "Back along the streets: the kitchen" }] },
  { id: "cellar", rot: 288, name: "The wine cellar", short: "Wine cellar", k: "L1 · The club", p: [79.67, -0.73], az0: 49, img: "pano/cellar.jpg",
    d: "Arcadia's one cellar, under vaults of brick fired from Mars soil: a tasting room with an oak table for ten under an iron chandelier, and aisles of racks and casks running 44 m along the ring each way.",
    links: [{ id: "cinema", label: "Back along the streets: the cinema" }] },
  { id: "pool", ready: false, rot: 216, name: "The lap pool", short: "Lap pool", k: "L1 · Baths and sport", p: [30.68, -69.71], az0: -105, img: "pano/pool.jpg",
    d: "Fifty metres and four lanes, 2 m deep, under a ceiling of oak slats with three slots of sky. In Mars' gravity a swimmer floats just as on Earth, but a splash rises nearly three times as high and falls slowly.",
    links: [{ id: "baths", label: "Through the street: the thermal baths" }] },
  { id: "lake", ready: false, rot: 216, name: "The lake", short: "Lake", k: "L2 · The garden, 41 m down", p: [25.83, -63.04], z: -16.7, az0: -40, img: "pano/lake.jpg",
    d: "Out on the jetty, under the sky of lamps 16 m up: a lake of 8,000 t of water, Arcadia's reserve you can see, with a beach behind the glass onto the atrium, a rowing boat, lilies and reeds, the columns that carry L1 standing in the water, and the stream from the forest falling in over the rocks.",
    links: [{ id: "bridge", at: [2.76, -28.26, -15.0], label: "Portal: up to L1" }] },

  /* The Crown, above ground, one stop in every room of the main floor (written by palace/tools/tour_crown.py):
     positions in metres from the ring's centre, x east, y north (the rooms lie between 118.5 and 135 m out, the
     Glide along the inner wall); z from the main floor, 41 m up. */
  { id: "crown_stars", place: "crown", ready: false, name: "The star lounge", short: "Star lounge", k: "The Crown · Observatory", p: [27.43, 124.77], az0: 18, img: "pano/crown_stars.jpg",
    d: "The Observatory at night: round daybeds for two laid back under the stars, a velvet crescent sofa, kentia palms in silhouette, and walls of glass that clear for the night sky. Across the ring the other rooms' windows glow.",
    links: [{ id: "crown_craft", at: [19.07, 115.18, 0], label: "The Glide: to the craft room" }, { id: "crown_telescope", at: [43.25, 119.14, 0], label: "Through to the telescope room" }, { id: "orb_earth", label: "Portal: up to the Orb" }] },
  { id: "crown_telescope", place: "crown", ready: false, name: "The telescope room", short: "Telescope room", k: "The Crown · Observatory", p: [57.83, 111.1], az0: -72, img: "pano/crown_telescope.jpg",
    d: "The control desk of the telescope in the dome above, with leather chairs at it, and a sofa facing the screens of what the telescope sees.",
    links: [{ id: "crown_stars", at: [43.25, 119.14, 0], label: "Through to the star lounge" }, { id: "crown_breakfast", at: [59.26, 100.6, 0], label: "The Glide: to the breakfast room" }] },
  { id: "crown_breakfast", place: "crown", ready: false, name: "The breakfast room", short: "Breakfast room", k: "The Crown · Garden room", p: [86.74, 88.26], az0: 22, img: "pano/crown_breakfast.jpg",
    d: "A round oak table for eight in upholstered chairs under a cluster of opal globes, an orchid on the table and lemon trees in pairs: late suppers under the stars, and breakfast at sunrise on a day off.",
    links: [{ id: "crown_telescope", at: [77.36, 87.44, 0], label: "The Glide: to the telescope room" }, { id: "crown_garden", at: [99.68, 78.3, 0], label: "Through to the sky garden" }] },
  { id: "crown_garden", place: "crown", ready: false, name: "The sky garden", short: "Sky garden", k: "The Crown · Garden room", p: [108.62, 64.75], az0: -96, img: "pano/crown_garden.jpg",
    d: "A conservatory in the ring: red and orange maples, a golden ginkgo, olive and lemon trees, tree ferns, beds of lavender and herbs, and daybeds under the trees, with grow lights overhead and the plain through the windows.",
    links: [{ id: "crown_breakfast", at: [99.68, 78.3, 0], label: "Through to the breakfast room" }, { id: "crown_suit", at: [103.27, 54.45, 0], label: "The Glide: to the suit room" }] },
  { id: "crown_suit", place: "crown", ready: false, name: "The suit room", short: "Suit room", k: "The Crown · Arrival", p: [122.77, 31.52], az0: -43, img: "pano/crown_suit.jpg",
    d: "The suits wait in their ports in the outer wall, so no dust comes in; a leather bench down the middle for the boots and a walnut counter for helmets and gloves.",
    links: [{ id: "crown_garden", at: [111.41, 34.91, 0], label: "The Glide: to the sky garden" }, { id: "crown_hangar", at: [124.88, 21.68, 0], label: "Through to the pod hangar" }] },
  { id: "crown_hangar", place: "crown", ready: false, name: "The pod hangar", short: "Pod hangar", k: "The Crown · Arrival", p: [125.21, 11.62], az0: -4, img: "pano/crown_hangar.jpg",
    d: "Arcadia's airlock: the pods fly in through the door in the outer wall, and the hangar fills with air in about 90 seconds while the dust is blown off them.",
    links: [{ id: "crown_suit", at: [124.88, 21.68, 0], label: "Through to the suit room" }, { id: "crown_door", at: [126.74, 1.88, 0], label: "Through to the Door" }] },
  { id: "crown_door", place: "crown", ready: false, name: "The Door", short: "The Door", k: "The Crown · Arrival", p: [126.5, -7.96], az0: 175, img: "pano/crown_door.jpg",
    d: "Arcadia's front door, a round opening 5 m across closed by an iris of light that knows Jim by face, eyes and walk; orange maples flank it and curved leather benches line the walls.",
    links: [{ id: "crown_hangar", at: [126.74, 1.88, 0], label: "Through to the pod hangar" }, { id: "crown_arrival", at: [126.03, -13.47, 0], label: "Through to the Arrival hall" }] },
  { id: "crown_arrival", place: "crown", name: "The Arrival hall", short: "Arrival", k: "The Crown · Arrival", p: [129.68, -19.61], az0: 145, img: "pano/crown_arrival.jpg",
    d: "20 m tall under the Arrival spire: the great maple, red and orange, in a round cognac banquette, a halo of light 12 m up, The Starry Night across the hall, and the portal to the Orb, the spires and the Pentagon.",
    links: [{ id: "crown_door", at: [126.03, -13.47, 0], label: "Through to the Door" }, { id: "crown_dressing", at: [114.37, -23.48, 0], label: "The Glide: to the dressing room up" }, { id: "bridge", at: [125.72, -39.4, 1.6], label: "Portal: down to the Pentagon" }] },
  { id: "crown_dressing", place: "crown", ready: false, name: "The dressing room up", short: "Dressing room", k: "The Crown · Master suite up", p: [116.72, -47.87], az0: -79, img: "pano/crown_dressing.jpg",
    d: "Walnut wardrobes 3.2 m tall along the outer wall, an island of drawers under a cluster of globes, a round velvet ottoman, and Matisse's Woman with a Hat.",
    links: [{ id: "crown_arrival", at: [110.19, -38.59, 0], label: "The Glide: to the Arrival hall" }, { id: "crown_bedroom", at: [112.02, -59.31, 0], label: "Through to the bedroom up" }] },
  { id: "crown_bedroom", place: "crown", name: "The bedroom up", short: "Bedroom up", k: "The Crown · Master suite up", p: [107.24, -70.98], az0: 49, img: "pano/crown_bedroom.jpg",
    d: "The grand bed against its wall of walnut and velvet under a halo of light, red maples either side; a sitting group under Monet's Water Lilies at the bath end, and Jim's desk at the other.",
    links: [{ id: "crown_dressing", at: [112.02, -59.31, 0], label: "Through to the dressing room up" }, { id: "crown_bath", at: [96.74, -81.9, 0], label: "Through to the bath up" }] },
  { id: "crown_bath", place: "crown", ready: false, name: "The bath up", short: "Bath up", k: "The Crown · Master suite up", p: [86.03, -92.26], az0: -135, img: "pano/crown_bath.jpg",
    d: "A soaking tub by the windows under alabaster pendants, a white leather chaise, a marble vanity 4 m long, a tree fern in the humid corner, and Hokusai's Great Wave.",
    links: [{ id: "crown_bedroom", at: [96.74, -81.9, 0], label: "Through to the bedroom up" }, { id: "crown_hearth", at: [75.05, -89.44, 0], label: "The Glide: to the hearth room" }] },
  { id: "crown_hearth", place: "crown", ready: false, name: "The hearth room", short: "Hearth room", k: "The Crown · Salon", p: [66.74, -111.97], az0: -28, img: "pano/crown_hearth.jpg",
    d: "A velvet crescent sofa round a marble table faces the hearth of lit mist in its stone wall, under Turner's Wreck of a Transport Ship; a golden ginkgo beside it.",
    links: [{ id: "crown_bath", at: [64.95, -97.02, 0], label: "The Glide: to the bath up" }, { id: "crown_salon", at: [54.77, -114.31, 0], label: "Through to the great salon" }] },
  { id: "crown_salon", place: "crown", ready: false, name: "The great salon", short: "Salon", k: "The Crown · Salon", p: [45.02, -121.05], az0: 86, img: "pano/crown_salon.jpg",
    d: "20 m tall under the Salon spire: boucle sofas across a travertine table, a velvet crescent round a marble table facing the windows, red and orange maples between the groups, and Kandinsky and Delaunay on the screen walls.",
    links: [{ id: "crown_hearth", at: [54.77, -114.31, 0], label: "Through to the hearth room" }, { id: "crown_piano", at: [30.13, -123.12, 0], label: "Through to the recital room" }] },
  { id: "crown_piano", place: "crown", ready: false, name: "The recital room", short: "Recital room", k: "The Crown · Salon", p: [15.81, -126.97], az0: 87, img: "pano/crown_piano.jpg",
    d: "The concert grand under a cluster of globes, two velvet crescents facing it, kentia palms either side, and Picabia's Udnie behind the audience.",
    links: [{ id: "crown_salon", at: [30.13, -123.12, 0], label: "Through to the great salon" }, { id: "crown_spa", at: [8.35, -116.45, 0], label: "The Glide: to the spa" }] },
  { id: "crown_spa", place: "crown", ready: false, name: "The spa", short: "Spa", k: "The Crown · Wellness", p: [-16.63, -124.65], az0: -130, img: "pano/crown_spa.jpg",
    d: "A round hot pool under low opal globes, a cold plunge, a cedar sauna with a glass front, daybeds in white leather, chaises at the windows, and tree ferns by the frosted glass.",
    links: [{ id: "crown_piano", at: [-9.36, -116.37, 0], label: "The Glide: to the recital room" }, { id: "crown_wellness", at: [-21.48, -124.92, 0], label: "Through to the sky pool" }] },
  { id: "crown_wellness", place: "crown", ready: false, name: "The sky pool", short: "Sky pool", k: "The Crown · Wellness", p: [-26.21, -124.27], az0: 74, img: "pano/crown_wellness.jpg",
    d: "A pool 25 m along the ring, lit from below, where low gravity makes every wave rise high and fall slowly; daybeds along the windows, kentias, maples and a fiddle-leaf fig along the inner side, halos over the water.",
    links: [{ id: "crown_spa", at: [-21.48, -124.92, 0], label: "Through to the spa" }, { id: "crown_gym", at: [-43.88, -118.91, 0], label: "Through to the gym" }] },
  { id: "crown_gym", place: "crown", ready: false, name: "The gym", short: "Gym", k: "The Crown · Wellness", p: [-60.39, -110.76], az0: 115, img: "pano/crown_gym.jpg",
    d: "Treadmills, bikes and rowers in a row facing the windows, a power rack before a mirror wall, mats for yoga by the glass, and Jim's photographs of Mars.",
    links: [{ id: "crown_wellness", at: [-43.88, -118.91, 0], label: "Through to the sky pool" }, { id: "crown_wine", at: [-61.18, -99.44, 0], label: "The Glide: to the wine room" }] },
  { id: "crown_wine", place: "crown", ready: false, name: "The wine room", short: "Wine room", k: "The Crown · Dining", p: [-81.34, -99.03], az0: -179, img: "pano/crown_wine.jpg",
    d: "The wine wall and the tasting counter under its globes, oxblood sofas facing across a travertine table by the glass, and a banquette under Caravaggio's Basket of Fruit.",
    links: [{ id: "crown_gym", at: [-69.28, -93.97, 0], label: "The Glide: to the gym" }, { id: "crown_dining", at: [-90.87, -88.37, 0], label: "Through to the dining hall" }] },
  { id: "crown_dining", place: "crown", ready: false, name: "The dining hall", short: "Dining hall", k: "The Crown · Dining", p: [-103.0, -79.89], az0: 21, img: "pano/crown_dining.jpg",
    d: "Under the Dining spire, one table of polished basalt for 22, high-backed velvet chairs, a line of halos down the table, lemon trees along the windows, and Van Gogh's olive trees and wheat field across the table.",
    links: [{ id: "crown_wine", at: [-90.87, -88.37, 0], label: "Through to the wine room" }, { id: "crown_kitchen", at: [-109.66, -63.57, 0], label: "Through to the chef's kitchen" }] },
  { id: "crown_kitchen", place: "crown", ready: false, name: "The chef's kitchen", short: "Chef's kitchen", k: "The Crown · Dining", p: [-118.11, -48.68], az0: 177, img: "pano/crown_kitchen.jpg",
    d: "Two islands of steel and marble under a halo, the cooking line under one long hood, the chef's table, and herbs in pots along the window.",
    links: [{ id: "crown_dining", at: [-109.66, -63.57, 0], label: "Through to the dining hall" }, { id: "crown_dayroom", at: [-110.12, -38.78, 0], label: "The Glide: to the guests' lounge" }] },
  { id: "crown_dayroom", place: "crown", ready: false, name: "The guests' lounge", short: "Guests' lounge", k: "The Crown · Sunset", p: [-122.61, -29.66], az0: 132, img: "pano/crown_dayroom.jpg",
    d: "The guests' day room up in the Crown: a sectional and two club chairs round a travertine table, two guest desks, a kitchenette, and Mondrian and Léger on the walls.",
    links: [{ id: "crown_kitchen", at: [-111.88, -33.35, 0], label: "The Glide: to the chef's kitchen" }, { id: "crown_sunset", at: [-125.86, -15.01, 0], label: "Through to the sunset lounge" }] },
  { id: "crown_sunset", place: "crown", ready: false, name: "The sunset lounge", short: "Sunset lounge", k: "The Crown · Sunset", p: [-126.75, -0.0], az0: 90, img: "pano/crown_sunset.jpg",
    d: "Long low sofas and a rust velvet crescent face the west windows, where at sunset the sun shines straight in for a few minutes and the sky round it turns blue; agaves and a golden ginkgo by the glass.",
    links: [{ id: "crown_dayroom", at: [-125.86, -15.01, 0], label: "Through to the guests' lounge" }, { id: "crown_gallery", at: [-125.87, 14.9, 0], label: "Through to the gallery" }] },
  { id: "crown_gallery", place: "crown", ready: false, name: "The gallery", short: "Gallery", k: "The Crown · Sunset", p: [-124.22, 29.82], az0: 113, img: "pano/crown_gallery.jpg",
    d: "The most paintings in the Crown, each under its own light, on both cross walls and on walls standing down the room; long leather benches, an old olive, and Van Gogh's Night Café between two kentias.",
    links: [{ id: "crown_sunset", at: [-125.87, 14.9, 0], label: "Through to the sunset lounge" }, { id: "crown_study", at: [-111.94, 33.16, 0], label: "The Glide: to the study up" }] },
  { id: "crown_study", place: "crown", ready: false, name: "The study up", short: "Study", k: "The Crown · Library", p: [-117.52, 47.48], az0: 96, img: "pano/crown_study.jpg",
    d: "Jim's walnut desk under an alabaster pendant, a reading sofa and Van Gogh's Self-Portrait with a Straw Hat: letters home in the evening, with Earth a star in the window.",
    links: [{ id: "crown_gallery", at: [-110.39, 38.01, 0], label: "The Glide: to the gallery" }, { id: "crown_library", at: [-110.43, 62.22, 0], label: "Through to the library up" }] },
  { id: "crown_library", place: "crown", ready: false, name: "The library up", short: "Library up", k: "The Crown · Library", p: [-99.09, 74.13], az0: 24, img: "pano/crown_library.jpg",
    d: "20 m tall under the Library spire: two floors of walnut shelves round a spiral stair, long reading tables under lamps, leather sofas by the windows and kentias between the shelves.",
    links: [{ id: "crown_study", at: [-110.43, 62.22, 0], label: "Through to the study up" }, { id: "crown_maproom", at: [-93.45, 85.63, 0], label: "Through to the map room" }] },
  { id: "crown_maproom", place: "crown", ready: false, name: "The map room", short: "Map room", k: "The Crown · Library", p: [-86.22, 96.43], az0: -79, img: "pano/crown_maproom.jpg",
    d: "A globe of Mars 3 m across, lit by washers, chests of map drawers, a long leather sofa facing the globe, and Claude Lorrain's Harbour with the Large Tower.",
    links: [{ id: "crown_library", at: [-93.45, 85.63, 0], label: "Through to the library up" }, { id: "crown_studio", at: [-73.16, 90.99, 0], label: "The Glide: to the art studio" }] },
  { id: "crown_studio", place: "crown", ready: false, name: "The art studio", short: "Art studio", k: "The Crown · Studio", p: [-59.25, 112.39], az0: 122, img: "pano/crown_studio.jpg",
    d: "Three easels by the windows, a work table under a halo of daylight white, a linen sofa and a cognac daybed on a big rug, a red maple and a bird of paradise, and Jim's big canvases on the end wall.",
    links: [{ id: "crown_maproom", at: [-59.78, 100.28, 0], label: "The Glide: to the map room" }, { id: "crown_prints", at: [-48.3, 117.19, 0], label: "Through to the print room" }] },
  { id: "crown_prints", place: "crown", ready: false, name: "The print room", short: "Print room", k: "The Crown · Studio", p: [-36.77, 120.26], az0: -55, img: "pano/crown_prints.jpg",
    d: "Jim's prints of Mars on both cross walls, a light table, the printers, a viewing sofa with club chairs, and a golden ginkgo by the glass.",
    links: [{ id: "crown_studio", at: [-48.3, 117.19, 0], label: "Through to the art studio" }, { id: "crown_craft", at: [-25.27, 124.21, 0], label: "Through to the craft room" }] },
  { id: "crown_craft", place: "crown", ready: false, name: "The craft room", short: "Craft room", k: "The Crown · Studio", p: [-13.14, 125.06], az0: -24, img: "pano/crown_craft.jpg",
    d: "The potter's wheel under a halo, workbenches, a board of drying pots, an olive and a lemon in terracotta; heavy work goes down to the workshops on L3.",
    links: [{ id: "crown_prints", at: [-25.27, 124.21, 0], label: "Through to the print room" }, { id: "crown_stars", at: [-6.11, 116.59, 0], label: "The Glide: to the star lounge" }] },
  { id: "orb_earth", place: "crown", ready: false, name: "The Earth lounge", short: "Earth lounge", k: "The Orb · +72 m", p: [12.09, 12.52], z: 31, az0: 213, img: "pano/orb_earth.jpg",
    d: "A lounge in the Orb with the universe switched on and zoomed to Earth: the lights down, the Earth floating in the room with the Moon beside it and the Sun far off, stars all round, and through the glass the Wormhole Gate showing a far nebula.",
    links: [{ id: "orb_mars", label: "Along the inner lane: the Mars lounge" }, { id: "crown_stars", label: "Portal: down to the Crown's star lounge" }] },
  { id: "orb_mars", place: "crown", ready: false, name: "The Mars lounge", short: "Mars lounge", k: "The Orb · +72 m", p: [15.64, -7.63], z: 31, az0: 141, img: "pano/orb_mars.jpg",
    d: "The next lounge round the Gate, the universe zoomed to Mars: the planet in its thin dusty air, Phobos and Deimos close by, stars all round.",
    links: [{ id: "orb_earth", label: "Along the inner lane: the Earth lounge" }, { id: "orb_galaxy", label: "Along the inner lane: the Galaxy lounge" }] },
  { id: "orb_galaxy", place: "crown", ready: false, name: "The Galaxy lounge", short: "Galaxy lounge", k: "The Orb · +72 m", p: [-17.14, -3.02], z: 31, az0: 357, img: "pano/orb_galaxy.jpg",
    d: "The Milky Way fills the room: two arms of blue-white stars wound round a golden core, tilted across the lounge. Here Jim chooses the far places the Gate will send him to.",
    links: [{ id: "orb_mars", label: "Along the inner lane: the Mars lounge" }, { id: "orb_earth", label: "Along the inner lane: the Earth lounge" }] }
];
window.TOUR_PHOTOS = [
  { img: "photos/hero.jpg", caption: "The family room on L1, from the fireplace end, looking out through the glass to the atrium and the portal column." },
  { img: "photos/living.jpg", caption: "The family room: the fire, the books and a skylight. The sofa, the chairs, the pouf, the plant and the flowers are 3D scans of real things." },
  { img: "photos/crown_salon.jpg", caption: "The great salon in the Crown, 20 m tall under its spire: boucle sofas round a travertine table under a cluster of opal globes, red and orange Japanese maples, the velvet crescent under a halo of light, the windows at eye level on the left and the wall of bronze and glass onto the Glide on the right." },
  { img: "photos/crown_bedroom.jpg", caption: "The master suite up in the Crown, 16.5 m deep and 12.5 m tall: the grand bed against its channelled headboard wall, lit from behind, alabaster pendants either side and a halo of light overhead; red Japanese maples; the morning sun through the south-east windows; behind, the suite's wall of bronze and frosted glass onto the Glide." },
  { img: "photos/library.jpg", caption: "The great library on L1: two storeys of books, a gallery reached by a spiral stair, reading tables under lamps, and daylight from the skylights." },
  { img: "photos/crown_library.jpg", caption: "The Crown's library, 20 m tall under its spire: two floors of walnut shelves round a spiral stair, a long reading table under lamps, leather sofas by the windows, a kentia by the glass wall onto the Glide." },
  { img: "photos/crown_maproom.jpg", caption: "The map room in the Crown's Library: a globe of Mars 3 m across in a bronze meridian, a long leather sofa facing it, Claude Lorrain's Harbour with the Large Tower under its light, the glass wall onto the Glide." },
  { img: "photos/baths.jpg", caption: "The thermal baths on L1: a warm pool of quartzite under slots of daylight from the sky ceiling, loungers, stone benches, and the atrium's olive trees through the glass." },
  { img: "photos/crown_dining.jpg", caption: "The dining hall in the Crown from the drinks lounge: the basalt table for 22 in claret velvet chairs under four halos of light, lemon trees along the windows, Van Gogh's Wheat Field with Cypresses at the far end." },
  { img: "photos/cinema.jpg", caption: "The cinema on L1: forty seats in claret velvet in four rising rows, walnut slats on the walls, sconces and lit steps, and a ceiling of 700 points of light, like stars." },
  { img: "photos/crown_wellness.jpg", caption: "The sky pool, 25 m along the ring: a line of chosen plants on the inner side, kentias, a red and an orange maple and a fiddle-leaf fig; halos over the water." },
  { img: "photos/crown_studio.jpg", caption: "The art studio in the Crown: a red maple by the glass onto the Glide, sculptures on white plinths, Jim's canvases on the easels and walls, globes of light over the sitting corner." },
  { img: "photos/crown_craft.jpg", caption: "The craft room: shelves of pots on the wall between the windows, the work tables, an olive and a lemon tree, under a halo of light." },
  { img: "photos/crown_stars.jpg", caption: "The star lounge in the Crown's Observatory at night: reclining chairs under the slots full of stars, candles on the side tables, a floor of polished basalt." },
  { img: "photos/crown_telescope.jpg", caption: "The telescope room in the Crown's Observatory at night: screens showing what the telescope sees, the Milky Way in the slots, and the portal up to the dome." },
  { img: "photos/crown_breakfast.jpg", caption: "The breakfast room in the Crown at sunrise: a round oak table for eight in upholstered chairs under a cluster of opal globes, an orchid on the table, and the first sun laid across the floor." },
  { img: "photos/crown_garden.jpg", caption: "The sky garden in the Crown: beds of herbs and flowers along both walls under small lemon and olive trees, grow lights on long cables, the morning sun on the inner wall." },
  { img: "photos/guests.jpg", caption: "The guest lounge: sofas by the glass, the table for twelve, the gallery of the guest suites." },
  { img: "photos/cellar.jpg", caption: "The wine cellar: the tasting table under the iron chandelier, an aisle of racks and casks beyond the arch." },
  { img: "photos/cellar2.jpg", caption: "Down an aisle of the wine cellar: racks and casks between the brick ribs, the tasting room at the end." },
  { img: "photos/suite_bedroom.jpg", caption: "The bedroom down: the bed against its panelled wall, walnut and oak, the lamps lit for the evening." },
  { img: "photos/suite_garden.jpg", caption: "The moss garden: a maple, a stone lantern and a pool among the rocks, open to the light from above." },
  { img: "photos/suite_bath.jpg", caption: "The bath down: the vanity on its green marble wall, the shower and the bath." },
  { img: "photos/memory.jpg", caption: "The memory rooms: Jim's photographs hung close on the deep green wall, the cases of keepsakes." },
  { img: "photos/memory2.jpg", caption: "The memory rooms from the memoir desk: the cases, the reading table, the doorway to the next room." },
  { img: "photos/crown_arrival.jpg", caption: "The Arrival hall in the Crown, looking back to the Door and its ring of light: the great maple, red turning orange, in its round banquette of cognac leather under a halo of light; the plain through the windows." },
  { img: "photos/music.jpg", caption: "The music room: the grand piano by the glass onto the atrium, a velvet sofa to listen from." },
  { img: "photos/dining.jpg", caption: "The dining room: the table for eight under five glass globes, by the glass onto the atrium." },
  { img: "photos/kitchen.jpg", caption: "The kitchen: the island for breakfast, the open shelves lit from within, the robot that cooks on its rail, the table for four." },
  { img: "photos/guests2.jpg", caption: "The guest lounge from the gallery: the sitting room below and the atrium through the glass." },
  { img: "photos/crown_suite_door.jpg", caption: "The master suite's doors on the Glide: a pair of walnut pivot doors 4 m tall with long bronze pulls, set in the suite's wall of bronze and frosted glass, lit by alabaster pendants." },
  { img: "photos/crown_salon2.jpg", caption: "Across the great salon from the recital room: the orange maple, the crescent groups round their tables, and at the far end Turner's sea over the hearth." },
  { img: "photos/crown_hearth.jpg", caption: "The hearth room in the Crown: a long hearth of lit mist at the foot of a basalt wall, Turner's Wreck of a Transport Ship over it, a rust velvet crescent, a gold ginkgo, and the walnut doors in the glass onto the Glide." },
  { img: "photos/crown_wellness2.jpg", caption: "The sky pool from the gym end: daybeds in pairs along the windows, and the wall of bronze and glass onto the Glide." },
  { img: "photos/crown_spa.jpg", caption: "The spa: the round hot pool lit under its rim, opal globes over it, tree ferns by the glass, chaises at the windows." },
  { img: "photos/crown_gym.jpg", caption: "The gym: treadmills, bikes and rowers facing the windows, a floor for free training, the weights before the mirror wall." },
  { img: "photos/crown_wine.jpg", caption: "The wine room: the wine wall lit from behind, a tasting group in oxblood leather, the serving island under its globes." },
  { img: "photos/crown_wine2.jpg", caption: "The wine room from the windows: the banquette and club chairs under a halo, Caravaggio's Basket of Fruit." },
  { img: "photos/crown_kitchen_up.jpg", caption: "The chef's kitchen in the Crown: two islands of steel under a halo of light and the long hood, the chef's table in green leather under opal globes, a wall of walnut cupboards." },
  { img: "photos/crown_kitchen_up2.jpg", caption: "The chef's kitchen: the cooking line and its open shelves under the long hood, the steel island, copper pendants, and frosted glass onto the Glide." },
  { img: "photos/crown_dining2.jpg", caption: "The dining hall from the kitchen end: the long table under its halos, Van Gogh's Olive Trees on the far wall, the gold ginkgo by the glass onto the Glide." },
  { img: "photos/crown_sunset.jpg", caption: "The sunset lounge in the Crown: long low sofas and a rust velvet crescent face the west windows, the sun low in them laying bars of light across the floor." },
  { img: "photos/crown_sunset2.jpg", caption: "The sunset lounge from the windows: the long sofa under two halos of light, the orange and red maples by the glass onto the Glide, agaves along the windows." },
  { img: "photos/crown_prints.jpg", caption: "The print room: Jim's photographs of Mars on the cross wall, the plan chest with prints laid out to choose from, a desk with its screen between the windows, a golden ginkgo by the glass." },
  { img: "photos/crown_gallery.jpg", caption: "The gallery: Van Gogh's Night Caf\u00e9 on the cross wall, Jim's photographs of Mars on the wall that stands down the middle, sculptures on plinths, the late sun across the oak floor." },
  { img: "photos/crown_dressing.jpg", caption: "The dressing room up: a round velvet ottoman, the triple mirror, a sitting corner by the windows." },
  { img: "photos/crown_bath_up.jpg", caption: "The bath up: a bathing pool of black basalt in the middle, the stone tub between two windows, chaises and kentia palms." },
  { img: "photos/crown_bath_up2.jpg", caption: "The bath up from the pool: the tub between the windows, alabaster lamps over it." },
  { img: "photos/crown_day_room.jpg", caption: "The guests' lounge: desks on the wall between the windows, a games table under a halo, a red maple." },
  { img: "photos/crown_suit.jpg", caption: "The suit room: steel lockers between the windows, the airlock at the end, club chairs and agaves." },
  { img: "photos/crown_hangar.jpg", caption: "The pod hangar: both pods home on their pads, lines of light in the ceiling, palms by the way to the Door." }
];
