"""The furnishing program: what each room holds, planned before it is drawn (AGENTS.md, "Furniture fits the rooms, and
every plant is chosen"). For each room: its seating (sized to the room: in a room of 400 m2 people sit on long sofas
and deep sectionals, groups facing their table, never on small chairs), its tables, its lights (the Crown's rooms are
12.5 m tall and 20 m under the spires: halos, clusters of globes, pendants dropping low, washers on the walls), its
plants (chosen for the room, species from palace/tools/render/plants.py), its paintings (public-domain works fetched
by fetch_art.py, each hung once, in the room it suits; art.py hangs them) and, where a room needs privacy, its doors. The pieces are in palace/tools/render: seating.py, tables.py, lights.py, bed.py, plants.py,
art.py. Crown rooms are revision H (palace/docs/crown-rev-h.md): 16.5 m from the Glide's edge to the outer wall.
Keys: the room codes of room_program.py. 'done' marks a room built to its program."""

CROWN = {
    "C-01": dict(name="Suit room", seating=["a leather bench 4 m long down the middle, for the boots", "a pair of leather club chairs by the airlock, to wait in"],
                 tables=["a walnut counter for helmets and gloves", "a drum between the club chairs"],
                 lights=["linear lights over the lockers", "an oak-slat ceiling lit from its coves", "a halo 4 m across over the bench", "washers"],
                 plants=[("agave", "blue, a row in basalt bowls under the windows, tough plants for a tough room"), ("kentia palm", "3 m, by the glass")],
                 art=["Jim's photograph of the Port at lift-off, 2.4 m, on the cross wall"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, frosted; a pivot door; the airlock's doors at the near end"),
    "C-02": dict(name="Pod hangar", seating=["a leather bench by the Door end, for whoever waits for a pod"], tables=["tool chests along the glass", "a charging post at each pad"],
                 lights=["floodlights over the pads", "five long lines of light in the ceiling, daylight white", "washers on both walls", "a lit ring round each pad"],
                 plants=[("kentia palm", "3.4 m, a pair at the Door end, where the house begins")], art=[],
                 layout="both pods home, each on its pad with its lit ring, noses to the great door",
                 doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, frosted; a pivot door; the pod door in the outer wall; the Door (C-03) to the house"),
    "C-03": dict(name="The Door", seating=["a curved leather bench along each side wall"], tables=[],
                 lights=["the iris of light round the Door"], plants=[("japanese maple", "orange, 4.5 m, a pair flanking the Door, in round basalt planters")],
                 art=[], doors="the Door, a ring of light 5 m across"),
    "C-04": dict(name="Arrival hall", seating=["a round banquette 7 m across wrapped round the great maple's planter, in cognac leather"],
                 tables=[], lights=["a halo 8 m across 12 m up, under the spire", "washers on both walls"],
                 plants=[("japanese maple", "red and orange, 5.5 m, the hall's great tree, multi-stemmed, in a round basalt planter 3.2 m across"),
                         ("kentia palm", "3.5 m, a pair by the portal"), ("agave", "blue, in travertine bowls along the windows")],
                 art=["Van Gogh's The Starry Night, 4.2 m wide, on the cross wall facing the arrivals"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; two pairs of pivot doors 3 m wide"),
    "C-06": dict(name="Dressing room", seating=["a round velvet ottoman 1.6 m across in the middle", "a chaise by the window",
                                              "a sitting corner by the windows: a velvet sofa 3.2 m and two club chairs round a marble table, on its own rug"],
                 tables=["an island of walnut drawers with a marble top, 4 m", "walnut wardrobes 3.2 m tall along both cross walls", "a triple mirror in bronze, 2.3 m tall, facing the ottoman"],
                 lights=["a cluster of globes over the island", "lit wardrobes", "a halo over the ottoman", "an arched lamp by the sofa"],
                 plants=[("orchid", "white, on the island"), ("kentia palm", "3.2 m, a pair by the frosted glass"), ("fiddle-leaf fig", "2.6 m, by the sofa")],
                 art=["Matisse's Woman with a Hat on the cross wall"], doors="the master suite's doors onto the Glide: a pair of walnut pivot doors 2.6 m wide and 4 m tall in the suite's glass wall"),
    "C-07": dict(name="Bedroom up", done=True,
                 seating=["the grand bed, 2.4 m wide, against a channelled headboard wall 6.4 m wide (bed.grand_bed)",
                          "a boucle sofa 4.6 m and two moss velvet club chairs round a travertine table, at the bath end",
                          "two rust velvet club chairs at the windows in front of the bed", "a leather executive chair at the desk"],
                 tables=["walnut nightstands floating from the headboard wall", "a travertine slab table 2.2 m", "a travertine drum",
                         "a writing desk of walnut, leather and bronze, 2.6 m"],
                 lights=["a halo 3.8 m across over the bed", "alabaster pendants either side of the bed and over the desk",
                         "the headboard lit from behind", "an arched lamp by the sofa", "washers on both walls"],
                 plants=[("japanese maple", "red, 3.4 m, a pair in basalt planters either side of the bed"), ("kentia palm", "3.4 m, the sitting corner"),
                         ("fiddle-leaf fig", "2.8 m, by the desk"), ("orchid", "white on the nightstands, magenta on the desk")],
                 art=["Monet's Water Lilies, 3 m, at the bath end", "Van Gogh's Starry Night over the Rhône, 2.4 m, at the desk end"],
                 doors="the suite's glass wall onto the Glide, frosted; open doorways to the dressing room and the bath"),
    "C-08": dict(name="Bath up", seating=["a chaise longue in white leather by the tub", "a teak bench in the shower", "two daybeds in the sunny corner",
                                        "two white leather chaises beside the bathing pool"],
                 tables=["a double vanity of marble 4 m long", "a stone stool by the tub", "drums with towels by the pool"],
                 lights=["alabaster pendants over the tub", "lit mirrors", "a halo over the pool", "the pool lit from below"],
                 layout="in the middle of the room, a bathing pool of black basalt 6 m by 2.6 m inside a rim 0.45 m high, warm and lit from below",
                 plants=[("tree fern", "2.8 m, the humid corner"), ("orchid", "white, on the vanity"), ("kentia palm", "a group of three along the frosted glass"),
                         ("bird of paradise", "at the pool's far end")], art=["Hokusai's The Great Wave off Kanagawa"],
                 doors="the suite's frosted glass; the lavatory behind its own door"),
    "C-09": dict(name="Hearth room", seating=["a velvet crescent sofa 6.4 m round a round marble table, facing the hearth", "two club chairs", "a leather ottoman"],
                 tables=["a round marble table 1.6 m", "drums"], lights=["the hearth of lit mist, 4 m long, in a stone wall", "a halo"],
                 plants=[("ginkgo", "gold, 4.5 m")], art=["Turner's The Wreck of a Transport Ship, 3.6 m, over the hearth"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors into the hearth room"),
    "C-10": dict(name="Great salon", seating=["two boucle sofas 5.2 m facing each other across a travertine table 2.6 m, with two club chairs (by the hearth room)",
                                              "a velvet crescent sofa 8 m round a round marble table under the spire, facing the windows, two daybeds beside it",
                                              "a sectional 5 x 4 m with two ottomans (by the recital room)"],
                 tables=["a travertine slab 2.6 m", "a round marble table 1.8 m", "a stacked travertine table", "drums"],
                 lights=["a halo 8 m across 12 m up under the spire", "clusters of globes over each table", "arched lamps", "washers"],
                 plants=[("japanese maple", "red 4.5 m and orange 4 m, between the groups"), ("kentia palm", "3.5 m, a pair at each group"),
                         ("bird of paradise", "3.5 m, by the windows"), ("orchid", "on the tables")],
                 art=["Kandinsky's Composition VII, 3.4 m, on the west screen wall", "Delaunay's Landscape with Disc, 3 m tall, on the east screen wall"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; two pairs of pivot doors into the great salon"),
    "C-11": dict(name="Recital room", seating=["two velvet crescent sofas facing the concert grand", "a long leather bench at the back"],
                 tables=[], lights=["globes over the piano", "washers"], plants=[("kentia palm", "a pair flanking the piano")],
                 art=["Picabia's Udnie (The Dance) behind the audience"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors into the recital room"),
    "C-13": dict(name="Spa", seating=["two daybeds in white leather by the hot pool", "two chaises facing the windows at the far end, for the rest between heat and cold",
                                     "the sauna's cedar benches"],
                 tables=["travertine drums"], lights=["a cluster of opal globes low over the hot pool", "a glow under its rim",
                                                      "a halo 4 m across over the chaises", "washers, warm and soft"],
                 plants=[("tree fern", "a group of three by the glass"), ("boxwood", "clipped balls along the windows"), ("orchid", "white, on the drum")], art=[],
                 doors="a door in the suite of frosted glass on the Glide; the sauna's glass door"),
    "C-14": dict(name="Sky pool", seating=["daybeds in pairs along the windows, facing the water"],
                 tables=["drums with towels between them"], lights=["lights under the water", "three halos 4 m across over the pool"],
                 plants=[("kentia palm", "3.6 m and 3.3 m, at the two ends of the inner side"), ("japanese maple", "red, 3.4 m, in a round basalt planter"),
                         ("fiddle-leaf fig", "2.8 m, in the middle of the inner side"), ("japanese maple", "orange, 3.6 m"),
                         ("bird of paradise", "at the pool's ends, by the windows")], art=[],
                 doors="none: clear glass onto the Glide, so the water is seen in passing"),
    "C-15": dict(name="Gym", seating=["a leather bench 3 m along the glass"],
                 tables=["a row facing the windows: four treadmills, three studio bikes, two rowers", "a power rack and two weight benches before a mirror wall",
                         "a rack of dumbbells", "six mats for yoga by the glass"],
                 lights=["three halos 5 m across", "washers"],
                 plants=[("fiddle-leaf fig", "a pair either end of the bench"), ("japanese maple", "orange, 3.6 m, by the mats"),
                         ("olive", "3 m, in the window corner"), ("kentia palm", "3.4 m, in the far corner")],
                 art=["Jim's photographs of Mars, framed 2.4 m wide: a lift-off at the Port and Mars with Earth, on the cross wall"],
                 doors="a door in frosted glass on the Glide"),
    "C-16": dict(name="Wine room", seating=["a leather banquette 4 m along the cross wall, a stone table in front, two club chairs",
                                          "for tastings, two oxblood sofas 3.2 m facing across a travertine table by the glass"], tables=["the tasting counter"],
                 lights=["globes over the counter", "a halo over each group", "washers"],
                 plants=[("olive", "2.5 m in terracotta"), ("japanese maple", "red, 3.6 m, at the windows"), ("kentia palm", "3.4 m, by the glass at the wine wall's end")],
                 art=["Caravaggio's Basket of Fruit"], doors="none"),
    "C-17": dict(name="Dining hall", seating=["22 high-backed velvet dining chairs, 58 cm wide"], tables=["one basalt table for 22, 14 m long", "two marble sideboards"],
                 lights=["a line of halos 3 m across down the table", "globes on the sideboards"],
                 plants=[("lemon", "four in terracotta along the windows"), ("olive", "a pair at the ends")],
                 art=["Van Gogh's Olive Trees and Wheat Field with Cypresses, 3.6 m each, a pair across the table"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; two pairs of pivot doors"),
    "C-18": dict(name="Chef's kitchen", seating=["a leather banquette for breakfast at the window"],
                 tables=["two prep islands of steel and marble", "the cooking line under one long hood"], lights=["pendants over the islands", "a halo 5 m across over them", "washers"],
                 plants=[("lavender", "herbs in pots along the window"), ("lemon", "2.6 m, by the banquette"), ("olive", "3.2 m, by the glass"), ("fiddle-leaf fig", "2.8 m, by the glass")],
                 art=[], doors="none"),
    "C-20": dict(name="Guests' lounge", seating=["a sectional 5 x 4 m and two club chairs round a travertine table, all facing it", "leather chairs at two guest desks",
                                              "a games table for four in leather club chairs, by the glass", "two lounge chairs facing the windows at the far end"],
                 tables=["a travertine table", "two walnut desks", "a kitchenette counter", "a square games table of walnut, 1.2 m"], lights=["globes", "desk pendants", "a halo over the games table"],
                 plants=[("fiddle-leaf fig", "2.6 m"), ("kentia palm", "3 m"), ("orchid", "on the desks"), ("japanese maple", "red, 4 m, in a round basalt planter between the groups")], art=["Mondrian's composition in yellow and grey", "Léger's Contrast of Forms"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, frosted for the guests; a pair of pivot doors"),
    "C-21": dict(name="Sunset lounge", seating=["two long low sofas 6 m facing the west windows", "two daybeds",
                                              "between them, a rust velvet crescent 6.4 m round a marble table, two club chairs"], tables=["long low travertine tables", "a round marble table"],
                 lights=["low lamps", "a warm halo over each group", "washers"],
                 plants=[("agave", "a bed of agaves and golden barrels by the windows"), ("ginkgo", "gold, to glow at sunset"),
                         ("japanese maple", "a red one by the glass behind the first group, an orange one beyond the crescent, 4.2 m")],
                 art=[], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; two pairs of pivot doors"),
    "C-22": dict(name="Gallery", seating=["long leather benches down the middle, museum style"], tables=[],
                 lights=["picture lights over every painting", "washers"], plants=[("olive", "one sculptural old olive"), ("kentia palm", "a pair flanking the Night Café on the far cross wall")],
                 art=["the most paintings in the Crown, on both cross walls and freestanding walls down the room: Van Gogh's The Night Café, Picabia's Edtaonisl, and the collection in turn", "two of Jim's big canvases, 2.6 m, on the cross walls beside the masterpieces", "four sculptures in bronze and marble on white plinths down the Glide side, each in its own light"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-23": dict(name="Study", seating=["a leather executive chair", "a reading sofa 4 m and a club chair"], tables=["Jim's day desk, walnut, 2.8 m"],
                 lights=["an alabaster pendant over the desk", "a halo"], plants=[("fiddle-leaf fig", "2.8 m")], art=["Van Gogh's Self-Portrait with a Straw Hat"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, frosted for Jim's desk; a pair of pivot doors"),
    "C-24": dict(name="Library", seating=["long leather sofas and club chairs by the windows", "leather chairs at the reading tables"],
                 tables=["two long reading tables of walnut"], lights=["a halo under the spire", "lamps on the tables"],
                 plants=[("kentia palm", "pairs between the shelves")], art=["Delaunay's Portrait of Jean Metzinger, the painter and writer, on the end wall"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; two pairs of pivot doors between the low bookcases"),
    "C-25": dict(name="Map room", seating=["a long leather sofa facing the globe"], tables=["map chests"], lights=["washers on the globe"],
                 plants=[("agave", "blue, in a basalt bowl")], art=["Claude Lorrain's etching The Harbour with the Large Tower"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-27": dict(name="Art studio", seating=["a linen sofa 5.2 m facing the easels, a daybed in cognac leather and two moss velvet club chairs round a table of art books, on a rug 7 x 5 m"],
                 tables=["a big work table 3.2 m", "a still-life table by the easels", "flat files along the glass"],
                 lights=["north light at the windows", "a halo 7 m across over the work, daylight white", "a cluster of globes over the sofa", "spots on the canvases", "washers"],
                 plants=[("bird of paradise", "3.5 m, by the glass"), ("fiddle-leaf fig", "2.6 m, in the corner by the windows"),
                         ("japanese maple", "red, 4 m, in a round basalt planter by the sofa"), ("kentia palm", "3.4 m, in the window corner by the print room")],
                 art=["Jim's canvases on three easels", "three of his big canvases, 2 to 2.8 m, on the end wall", "raw canvases leaning on the cross wall"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-28": dict(name="Photo and print room", seating=["a viewing sofa 4 m and two club chairs facing the prints"], tables=["a light table", "the printers", "a counter of screens"],
                 lights=["a halo 5 m across, daylight white", "washers"],
                 plants=[("ginkgo", "gold, 3.8 m, by the glass"), ("kentia palm", "3.2 m, by the counter")],
                 art=["Jim's prints of Mars on both cross walls"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-29": dict(name="Craft room", seating=["a leather banquette 3.4 m"], tables=["workbenches", "the potter's wheel", "a board of drying pots"],
                 lights=["a halo 5 m across over the wheel", "task lights", "washers"],
                 plants=[("olive", "3 m, in terracotta, in the window corner"), ("lemon", "2.4 m, in terracotta, by the glass")], art=[], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-30": dict(name="Star lounge", seating=["round daybeds 2.2 m across for two, laid back to the sky", "a velvet crescent sofa"], tables=["low drums"],
                 lights=["almost none at night; the switch by the door darkens the glass by day"], plants=[("kentia palm", "silhouettes against the stars")], art=[],
                 doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear (its inner and outer walls are switchable glass); a pair of pivot doors"),
    "C-31": dict(name="Telescope room", seating=["leather executive chairs at the control desk", "a sofa facing the screens"], tables=["the control desk"],
                 lights=["the screens", "desk pendants"], plants=[("kentia palm", "")], art=[], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-33": dict(name="Breakfast room", seating=["a round table for eight in upholstered chairs", "a banquette along the windows"], tables=["a round oak table 2.2 m"],
                 lights=["a cluster of globes over the table"], plants=[("lemon", "a pair"), ("orchid", "on the table")], art=["Van Gogh's thatched cottages in the sun, Auvers"], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear; a pair of pivot doors"),
    "C-34": dict(name="Sky garden", seating=["two daybeds by the basin", "a long stone bench facing it"], tables=[],
                 lights=["grow lights", "low path lights along every bed"],
                 layout=("paths of honed black basalt (Jim, 4 Oct: \"black platform\") between raised beds: beds along both walls, and two "
                         "island beds 15 m long down the middle, either side of a round basin with its bench and daybeds"),
                 plants=[("japanese maple", "red and orange, in the beds and the islands"), ("ginkgo", "gold"), ("olive", ""), ("lemon", ""), ("lavender", "beds"),
                         ("kentia palm", "a group in the first island"), ("bird of paradise", "in the first island"), ("golden barrel", "at the islands' ends"),
                         ("tree fern", "in the second island"), ("agave", "in the second island"), ("boxwood", "clipped balls at the beds' ends")],
                 art=[], doors="a wall of bronze and glass onto the Glide from the floor to the ceiling, as in the master suite, clear, so the garden is seen in passing; a pair of pivot doors"),
}
