"""The furnishing program: what each room holds, planned before it is drawn (AGENTS.md, "Furniture fits the rooms, and
every plant is chosen"). For each room: its seating (sized to the room: in a room of 400 m2 people sit on long sofas
and deep sectionals, groups facing their table, never on small chairs), its tables, its lights (the Crown's rooms are
12.5 m tall and 20 m under the spires: halos, clusters of globes, pendants dropping low, washers on the walls), its
plants (chosen for the room, species from palace/tools/render/plants.py), its paintings (art.py) and, where a room
needs privacy, its doors. The pieces are in palace/tools/render: seating.py, tables.py, lights.py, bed.py, plants.py,
art.py. Crown rooms are revision H (palace/docs/crown-rev-h.md): 16.5 m from the Glide's edge to the outer wall.
Keys: the room codes of room_program.py. 'done' marks a room built to its program."""

CROWN = {
    "C-01": dict(name="Suit room", seating=["a leather bench 4 m long down the middle, for the boots"],
                 tables=["a walnut counter for helmets and gloves"], lights=["linear lights over the lockers", "washers"],
                 plants=[], art=[], doors="the airlock's doors; the room is open to the Glide"),
    "C-02": dict(name="Pod hangar", seating=[], tables=[], lights=["floodlights over the pads"], plants=[], art=[],
                 doors="the pod door in the outer wall; the Door (C-03) to the house"),
    "C-03": dict(name="The Door", seating=["a curved leather bench along each side wall"], tables=[],
                 lights=["the iris of light round the Door"], plants=[("japanese maple", "orange, 4.5 m, a pair flanking the Door, in round basalt planters")],
                 art=[], doors="the Door, a ring of light 5 m across"),
    "C-04": dict(name="Arrival hall", seating=["a round banquette 7 m across wrapped round the great maple's planter, in cognac leather"],
                 tables=[], lights=["a halo 8 m across 12 m up, under the spire", "washers on both walls"],
                 plants=[("japanese maple", "red and orange, 5.5 m, the hall's great tree, multi-stemmed, in a round basalt planter 3.2 m across"),
                         ("kentia palm", "3.5 m, a pair by the portal"), ("agave", "blue, in travertine bowls along the windows")],
                 art=["two large paintings, one on each cross wall"], doors="none: everyone arrives here"),
    "C-06": dict(name="Dressing room", seating=["a round velvet ottoman 1.6 m across in the middle", "a chaise by the window"],
                 tables=["an island of walnut drawers with a marble top, 4 m", "walnut wardrobes 3.2 m tall along the outer wall"],
                 lights=["a cluster of globes over the island", "lit wardrobes"], plants=[("orchid", "white, on the island")],
                 art=["a painting on the cross wall"], doors="the master suite's doors onto the Glide: a pair of walnut pivot doors 2.6 m wide and 4 m tall in the suite's glass wall"),
    "C-07": dict(name="Bedroom up", done=True,
                 seating=["the grand bed, 2.4 m wide, against a channelled headboard wall 6.4 m wide (bed.grand_bed)",
                          "a boucle sofa 4.6 m and two moss velvet club chairs round a travertine table, at the bath end",
                          "two rust velvet club chairs at the windows in front of the bed", "a leather executive chair at the desk"],
                 tables=["walnut nightstands floating from the headboard wall", "a travertine slab table 2.2 m", "a travertine drum",
                         "a writing desk of walnut, leather and bronze, 2.6 m"],
                 lights=["a halo 3.8 m across over the bed", "alabaster pendants either side of the bed and over the desk",
                         "the headboard lit from behind", "an arched lamp by the sofa", "washers on both walls"],
                 plants=[("japanese maple", "red, 3.4 m, a pair in basalt planters either side of the bed"), ("kentia palm", "3.4 m, the sitting corner"),
                         ("fiddle-leaf fig", "2.8 m, by the desk"), ("orchid", "white on the nightstands, magenta on the desk")],
                 art=["a large painting on each cross wall, lit"],
                 doors="the suite's glass wall onto the Glide, frosted; open doorways to the dressing room and the bath"),
    "C-08": dict(name="Bath up", seating=["a chaise longue in white leather by the tub", "a teak bench in the shower"],
                 tables=["a double vanity of marble 4 m long", "a stone stool by the tub"],
                 lights=["alabaster pendants over the tub", "lit mirrors"],
                 plants=[("tree fern", "2.8 m, the humid corner"), ("orchid", "white, on the vanity")], art=["a print by Hokusai or Hiroshige"],
                 doors="the suite's frosted glass; the lavatory behind its own door"),
    "C-09": dict(name="Hearth room", seating=["a velvet crescent sofa 6.4 m round a round marble table, facing the hearth", "two club chairs", "a leather ottoman"],
                 tables=["a round marble table 1.6 m", "drums"], lights=["the hearth of lit mist, 4 m long, in a stone wall", "a halo"],
                 plants=[("ginkgo", "gold, 4.5 m")], art=["a large seascape over the hearth"], doors="none"),
    "C-10": dict(name="Great salon", seating=["two boucle sofas 5.2 m facing each other across a travertine table 2.6 m, with two club chairs (by the hearth room)",
                                              "a velvet crescent sofa 8 m round a round marble table under the spire, facing the windows, two daybeds beside it",
                                              "a sectional 5 x 4 m with two ottomans (by the recital room)"],
                 tables=["a travertine slab 2.6 m", "a round marble table 1.8 m", "a stacked travertine table", "drums"],
                 lights=["a halo 8 m across 12 m up under the spire", "clusters of globes over each table", "arched lamps", "washers"],
                 plants=[("japanese maple", "red 4.5 m and orange 4 m, between the groups"), ("kentia palm", "3.5 m, a pair at each group"),
                         ("bird of paradise", "3.5 m, by the windows"), ("orchid", "on the tables")],
                 art=["big paintings on both cross walls"], doors="none: the salon is open to the Glide"),
    "C-11": dict(name="Recital room", seating=["two velvet crescent sofas facing the concert grand", "a long leather bench at the back"],
                 tables=[], lights=["globes over the piano", "washers"], plants=[("kentia palm", "a pair flanking the piano")],
                 art=["a large figure painting (Klimt) behind the audience"], doors="none"),
    "C-13": dict(name="Spa", seating=["two daybeds in white leather by the hot pool", "the sauna's cedar benches"], tables=["stone stools"],
                 lights=["low lights round the pool"], plants=[("tree fern", "a group of three"), ("boxwood", "clipped balls")], art=[],
                 doors="the sauna's glass door"),
    "C-14": dict(name="Sky pool", seating=["daybeds along the windows"], tables=["drums with towels"], lights=["lights under the water"],
                 plants=[("kentia palm", "a row along the inner side"), ("bird of paradise", "at the pool's ends")], art=[], doors="none"),
    "C-15": dict(name="Gym", seating=["a leather bench 3 m"], tables=[], lights=["washers"], plants=[("fiddle-leaf fig", "a pair")], art=[], doors="none"),
    "C-16": dict(name="Wine room", seating=["a leather banquette 4 m along the cross wall, a stone table in front"], tables=["the tasting counter"],
                 lights=["globes over the counter"], plants=[("olive", "2.5 m in terracotta")], art=["a still life (Caravaggio's basket of fruit)"], doors="none"),
    "C-17": dict(name="Dining hall", seating=["22 high-backed velvet dining chairs, 58 cm wide"], tables=["one basalt table for 22, 14 m long", "two marble sideboards"],
                 lights=["a line of halos 3 m across down the table", "globes on the sideboards"],
                 plants=[("lemon", "four in terracotta along the windows"), ("olive", "a pair at the ends")],
                 art=["large paintings on both cross walls (Monet, Van Gogh)"], doors="none"),
    "C-18": dict(name="Chef's kitchen", seating=["a leather banquette for breakfast at the window", "bar stools with backs at the island"],
                 tables=["an island of steel and marble 6 m"], lights=["pendants over the island"], plants=[("lavender", "herbs in pots along the window")],
                 art=[], doors="none"),
    "C-20": dict(name="Guests' day room", seating=["a sectional 5 x 4 m and two club chairs round a travertine table, all facing it", "leather chairs at two guest desks"],
                 tables=["a travertine table", "two walnut desks", "a kitchenette counter"], lights=["globes", "desk pendants"],
                 plants=[("fiddle-leaf fig", "2.6 m"), ("kentia palm", "3 m"), ("orchid", "on the desks")], art=["abstract paintings (Kandinsky, Mondrian)"], doors="none"),
    "C-21": dict(name="Sunset lounge", seating=["two long low sofas 6 m facing the west windows", "two daybeds"], tables=["long low travertine tables"],
                 lights=["low lamps; the sunset does the rest"], plants=[("agave", "a bed of agaves and golden barrels by the windows"), ("ginkgo", "gold, to glow at sunset")],
                 art=[], doors="none"),
    "C-22": dict(name="Gallery", seating=["long leather benches down the middle, museum style"], tables=[],
                 lights=["picture lights over every painting", "washers"], plants=[("olive", "one sculptural old olive")],
                 art=["the most paintings in the Crown: both cross walls and freestanding walls down the room"], doors="none"),
    "C-23": dict(name="Study", seating=["a leather executive chair", "a reading sofa 4 m and a club chair"], tables=["Jim's day desk, walnut, 2.8 m"],
                 lights=["an alabaster pendant over the desk", "a halo"], plants=[("fiddle-leaf fig", "2.8 m")], art=["a Van Gogh"], doors="none"),
    "C-24": dict(name="Library", seating=["long leather sofas and club chairs by the windows", "leather chairs at the reading tables"],
                 tables=["two long reading tables of walnut"], lights=["a halo under the spire", "lamps on the tables"],
                 plants=[("kentia palm", "pairs between the shelves")], art=["a Turner"], doors="none"),
    "C-25": dict(name="Map room", seating=["a long leather sofa facing the globe"], tables=["map chests"], lights=["washers on the globe"],
                 plants=[("agave", "blue, in a basalt bowl")], art=["prints by Hiroshige"], doors="none"),
    "C-27": dict(name="Art studio", seating=["a daybed for looking at the work"], tables=["a big work table"], lights=["north light; daylight lamps"],
                 plants=[("bird of paradise", "3.5 m"), ("fiddle-leaf fig", "2.6 m")], art=["Jim's canvases on easels"], doors="none"),
    "C-28": dict(name="Photo and print room", seating=["a viewing sofa 4 m"], tables=["a light table", "the printers"], lights=["even daylight lamps"],
                 plants=[], art=["Jim's prints of Mars"], doors="none"),
    "C-29": dict(name="Craft room", seating=["a leather banquette"], tables=["workbenches", "the potter's wheel"], lights=["task lights"],
                 plants=[("olive", "in terracotta")], art=[], doors="none"),
    "C-30": dict(name="Star lounge", seating=["round daybeds 2.2 m across for two, laid back to the sky", "a velvet crescent sofa"], tables=["low drums"],
                 lights=["almost none at night; the switch by the door darkens the glass by day"], plants=[("kentia palm", "silhouettes against the stars")], art=[],
                 doors="its outer and inner walls of switchable glass, full height: dark by day, clear at night"),
    "C-31": dict(name="Telescope room", seating=["leather executive chairs at the control desk", "a sofa facing the screens"], tables=["the control desk"],
                 lights=["the screens", "desk pendants"], plants=[("kentia palm", "")], art=[], doors="none"),
    "C-33": dict(name="Breakfast room", seating=["a round table for eight in upholstered chairs", "a banquette along the windows"], tables=["a round oak table 2.2 m"],
                 lights=["a cluster of globes over the table"], plants=[("lemon", "a pair"), ("orchid", "on the table")], art=["a Monet"], doors="none"),
    "C-34": dict(name="Sky garden", seating=["daybeds under the trees", "a long stone bench"], tables=[],
                 lights=["grow lights", "low path lights"],
                 plants=[("japanese maple", "red and orange"), ("ginkgo", "gold"), ("olive", ""), ("lemon", ""), ("lavender", "beds"), ("bird of paradise", ""),
                         ("tree fern", ""), ("agave", ""), ("boxwood", "clipped balls")],
                 art=[], doors="none; its floor: a black platform (to be confirmed with Jim)"),
}
